version: '3'
services:
  django:
    image: python:3.7
    network_mode: bridge
    container_name: simpleskill
    volumes:
      - .:/code/
    ports:
      - 5000:8000
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=False
      - DJANGO_ALLOWED_HOSTS=*
    working_dir: /code
    command: >
      bash -c "pip install -r requirements.txt 
      && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
