# Generated by Django 4.0.4 on 2022-04-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tag_simpleskills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='simpleskills',
        ),
        migrations.AddField(
            model_name='simpleskill',
            name='tags',
            field=models.ManyToManyField(null=True, to='app.tag'),
        ),
    ]
