# Generated by Django 4.0.4 on 2022-04-21 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_tag_simpleskills_simpleskill_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisite',
            name='from_simpleskill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre', to='app.simpleskill'),
        ),
    ]
