# Generated by Django 4.0.3 on 2022-05-20 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='users_interested',
            field=models.ManyToManyField(related_name='interests', through='app.UserInterest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='app.milestone'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='simpleskill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='app.simpleskill'),
        ),
        migrations.AlterField(
            model_name='registeredsimpleskill',
            name='finished_materials',
            field=models.ManyToManyField(null=True, to='app.material'),
        ),
        migrations.AlterField(
            model_name='simpleskill',
            name='tags',
            field=models.ManyToManyField(related_name='simpleskills', to='app.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='app.category'),
        ),
    ]
