# Generated by Django 4.0.4 on 2022-04-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_prerequisite_from_simpleskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleskill',
            name='tags',
            field=models.ManyToManyField(to='app.tag'),
        ),
    ]
