# Generated by Django 4.0.4 on 2022-05-22 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterest',
            name='experience_level',
            field=models.IntegerField(choices=[(0, 'Beginner'), (1, 'Intermediate'), (2, 'Advanced')], default=0),
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='interest_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
