# Generated by Django 4.0.4 on 2022-05-22 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_userinterest_experience_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredsimpleskill',
            name='date_started',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
