# Generated by Django 4.0.4 on 2022-05-23 08:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_registeredsimpleskill_date_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedSimpleskill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_finished', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='simpleskill',
            name='users_finished',
            field=models.ManyToManyField(related_name='finished_simpleskills', through='app.FinishedSimpleskill', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finishedsimpleskill',
            name='simpleskill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.simpleskill'),
        ),
        migrations.AddField(
            model_name='finishedsimpleskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
