# Generated by Django 4.0.4 on 2022-05-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_finishedsimpleskill_simpleskill_users_finished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.IntegerField(choices=[(0, 'Article'), (1, 'Video'), (2, 'Project'), (3, 'Game'), (4, 'Other')]),
        ),
    ]
