# Generated by Django 4.0.4 on 2022-05-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_material_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='title',
        ),
    ]
